baseURL = "https://sammyette.party/"
title = "sammyette's place"
theme = "sakura"
languageCode = "en-US"
enableInlineShortcodes = true

[params]
  lightSakura = "sakura"
  darkSakura = "sakura-vader"

[permalinks]
  blogs = "/:title/"

[markup.goldmark.renderer]
  unsafe = true
