name = "sakura"
license = "MIT"
licenselink = "https://github.com/TorchedSammy/torchedsammy.github.io/blob/master/LICENSE"
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
